### ISSUE TITLE
crashes on load up

### ISSUE THREAD

**Issue by Yellerimp** [Sephta/stal-alloys#3]
The game crashed whilst ticking block entity
Error: java.util.NoSuchElementException: net.stal.alloys.block.entity.AlloySmelterEntity@15c7e2a8 provides no component of type polymorph:block_entity_recipe_data

This was the error message.

**Comment by Sephta** [comment]
Hello! This seems to be indicative of an incompatibility with the polymorph mod. I'll look into this when I have time. Thank you for reporting this issue.

**Comment by Sephta** [comment]
If you have access to the full error log file I would appreciate if you could provide that here. Also if you know what version of my mod you were using that would help as well.

**Comment by Yellerimp** [comment]
It should be the most recent version of the mod, used in 1.21

**Comment by Sephta** [comment]
Hello @Yellerimp I brought up this issue with the developer of Polymorph and they've updated the their mod to address it. I tested the lastest version of Polymorph alongside my own mod and it seems to work fine on my end in 1.21. I'm going to close this issue as addressed but feel free to create another post here or contact the Polymorph developer if you're having similar problems in the future.
